spring:
  datasource:
    url: jdbc:h2:mem:JWTSECURITY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER;MODE=LEGACY
    username: sa
    password: null
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080
  stateless: false

management:
  beans:
    enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,metrics,env,beans

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data